[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
guardian_vault = "DwuGR9qYkgYUPxR6jZSkAHdv23YPeqaAwxLAG593L1ar"

[programs.devnet]
guardian_vault = "DwuGR9qYkgYUPxR6jZSkAHdv23YPeqaAwxLAG593L1ar"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/cmpgfb/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
init-guardians = "npx ts-node scripts/init_mainnet_guardians.ts"

